### ISSUE TITLE
Can't remove a repo

### ISSUE THREAD

**Issue by MoBlockbuster** [merll/docker-registry-util#10]
hi,

i installed dregutil by pip3 on a centos8 machine in a test-lab.

with dregutil i can check my repos and tags, but if i want to delete a repo, i get this python error (ignore the certificate message):

[root@docker-test ~]# dregutil --registry 192.168.56.101:443 -v /etc/docker/certs.d/192.168.56.101/ca.crt --user bob --password test remove-repos -r alpine
2020-10-12 21:46:24,290 [INFO] docker_registry_util.remover - Removing digest sha256:a15790640a6690aa1730c38cf0a440e2aa44aaca9b0e8931a9f2b0d7cc90fd65.
/usr/lib/python3.6/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for 192.168.56.101 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning

Traceback (most recent call last):
  File "/usr/local/bin/dregutil", line 11, in <module>
    load_entry_point('docker-registry-util==1.0.3', 'console_scripts', 'dregutil')()
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 291, in main
    args.func(q)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 180, in remove_repos
    result = remover.remove_repositories(args.repo, raise_intersecting_repo=args.raise_intersecting_repo)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/remover.py", line 33, in remove_repositories
    client.delete_manifest(name, digest.as_sha256())
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 83, in delete_manifest
    return self._request('DELETE', name, 'manifests', reference)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 37, in _request
    res.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://192.168.56.101:443/v2/alpine/manifests/sha256:a15790640a6690aa1730c38cf0a440e2aa44aaca9b0e8931a9f2b0d7cc90fd65

what can we do in this case?

cheers

**Comment by MoBlockbuster** [comment]
the same message with:

pip3 install git+https://github.com/merll/docker-registry-util.git




Traceback (most recent call last):
  File "/usr/local/bin/dregutil", line 11, in <module>
    load_entry_point('docker-registry-util==1.0.3', 'console_scripts', 'dregutil')()
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 291, in main
    args.func(q)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 180, in remove_repos
    result = remover.remove_repositories(args.repo, raise_intersecting_repo=args.raise_intersecting_repo)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/remover.py", line 33, in remove_repositories
    client.delete_manifest(name, digest.as_sha256())
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 83, in delete_manifest
    return self._request('DELETE', name, 'manifests', reference)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 37, in _request
    res.raise_for_status()
  File "/usr/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://192.168.56.101:443/v2/alpine/manifests/sha256:a15790640a6690aa1730c38cf0a440e2aa44aaca9b0e8931a9f2b0d7cc90fd65
