### ISSUE TITLE
Syntax error running query-repos

### ISSUE THREAD

**Issue by Raketemensch** [merll/docker-registry-util#2]
I'm getting this error when trying to query our registry after a fresh install with Python 2.6.6:

Traceback (most recent call last):
  File "/usr/bin/dregutil", line 11, in <module>
    load_entry_point('docker-registry-util==1.0.2', 'console_scripts', 'dregutil')()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 2255, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/docker_registry_util/cli.py", line 12, in <module>
    from .query import DockerRegistryQuery
  File "/usr/lib/python2.6/site-packages/docker_registry_util/query.py", line 196
    current_tags = {i[1] for i in repo_tags}
                           ^
SyntaxError: invalid syntax

**Comment by merll** [comment]
The quoted error is just a dictionary comprehension that could be avoided, but the command line utility is also using ``argparse``. Both were new in Python 2.7.

Docker-Registry-Util is currently implemented in Python 3. If there is enough interest it could be ported to Python 2.7; providing backwards compatibility to Python 2.6 however does not seem very useful to me compared to the work involved. Python 2.6 is no longer maintained since 2013, and its support is being dropped from other libraries as well.
