### ISSUE TITLE
Error in requests

### ISSUE THREAD

**Issue by Toonix** [merll/docker-registry-util#4]
I get the error unauthorized even when I specify user and password.

Which version of request is needed?

`File "c:\users\5610\appdata\local\programs\python\python36-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:`

I got installed:

`pip freeze
beautifulsoup4==4.6.0
certifi==2017.7.27.1
chardet==3.0.4
click==6.7
docker-registry-util==1.0.3
ez-setup==0.9
Flask==0.12.2
Flask-Login==0.4.0
idna==2.6
itsdangerous==0.24
Jinja2==2.9.6
ldap==1.0.2
ldap3==2.3
MarkupSafe==1.0
numpy==1.13.3
pandas==0.21.0
pyasn1==0.3.7
pymongo==3.5.1
python-dateutil==2.6.1
pytz==2017.3
requests==2.18.4
six==1.11.0
urllib3==1.22
Werkzeug==0.12.2
`

**Comment by merll** [comment]
The request version should be just fine.

The HTTP error with code 401 (Unauthorized) means that the login to the registry did not work. Did you add user name / password to the command line? Or are you using certificates? If the local ``docker login`` has been used before and stored its authentication data, the utility could also read that information.

**Comment by Toonix** [comment]
docker login just works fine. But login over the command line tool didn't work. I entered -u and -p and of course -reg and I tried it over env settings.

**Comment by merll** [comment]
Does this already occur while querying tags, or when attempting to remove? Could you please post the complete stack trace and the URL path (you can leave out or change the host name if you want)?

**Comment by Toonix** [comment]
C:\Users\xxxxxxxx>dregutil -u xxxxxx -p xxxxxxxxxx-reg gitdev.xxx.com:5005 list-repo-names
2017-12-07 08:50:59,301 [INFO] docker_registry_util.query - Initializing cache.
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Local\Programs\Python\Python36-32\Scripts\dregutil-script.py", line 11, in <module>
    load_entry_point('docker-registry-util==1.0.3', 'console_scripts', 'dregutil')()
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\cli.py", line 291, in main
    args.func(q)
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\cli.py", line 144, in list_repo_names
    result = query.get_repo_names()
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\query.py", line 284, in get_repo_names
    self.refresh()
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\query.py", line 131, in refresh
    repos = self._client.get_catalog().json()['repositories']
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\client.py", line 68, in get_catalog
    return self._request('GET', '_catalog')
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\docker_registry_util\client.py", line 37, in _request
    res.raise_for_status()
  File "c:\users\xxxxxxxx\appdata\local\programs\python\python36-32\lib\site-packages\requests\models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://gitdev.xxxx.com:5005/v2/_catalog

**Comment by merll** [comment]
So if you open the URL in the browser, manually enter user name and password, does that return a list of repositories?

**Comment by Toonix** [comment]
There is no Basic Authentication in the Browser and I hadn't anyluck with curl either...was using --anyauth and --digest.

Well but docker login works gitdev.xxx.com:5005

**Comment by Toonix** [comment]
Ok looks like I found out the problem.

I'm Using gitlab with the included Registry. If you try to authenticate to 

https://gitdev.xxxx.com/jwt/auth",service="container_registry",scope="registry:catalog:*

then you get Redirected to:

https://gitdev.xxxx.com/user/sign_in


https://about.gitlab.com/2016/05/23/gitlab-container-registry/
