### ISSUE TITLE
access to registry by token?

### ISSUE THREAD

**Issue by dober** [merll/docker-registry-util#5]
Hello!
Probably this is feature request
Im using externl auth service https://github.com/cesanta/docker_auth
And docker-registry-util doesnt work with it :(

`dregutil --registry https://myregistry--user admin --password password list-repo-names
2017-12-11 16:44:04,121 [INFO] docker_registry_util.query - Initializing cache.
Traceback (most recent call last):
  File "/usr/local/bin/dregutil", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 291, in main
    args.func(q)
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/cli.py", line 144, in list_repo_names
    result = query.get_repo_names()
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/query.py", line 284, in get_repo_names
    self.refresh()
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/query.py", line 131, in refresh
    repos = self._client.get_catalog().json()['repositories']
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 68, in get_catalog
    return self._request('GET', '_catalog')
  File "/usr/local/lib/python3.6/site-packages/docker_registry_util/client.py", line 37, in _request
    res.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://myregistry/v2/_catalog`

What about token access feature?

**Comment by glensc** [comment]
I have the same problem, how to access docker registry with jwt based token auth, like [gitlab registry](https://docs.gitlab.com/ce/user/project/container_registry.html)

docs how to setup docker registry with token auth: https://docs.docker.com/registry/spec/auth/token/
